-- CYEZ 乒乓球积分系统 - Supabase 数据库初始化脚本
-- 在 Supabase Dashboard -> SQL Editor 中一次性执行。
-- 说明：本方案使用 Supabase Auth + PostgreSQL + RLS + Realtime。

create extension if not exists pgcrypto;

create schema if not exists private;

-- =========================
-- 1) 选手资料
-- =========================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  real_name text not null check (char_length(trim(real_name)) between 1 and 40),
  username text not null unique check (username = lower(username) and char_length(username) between 3 and 24),
  role text not null default 'player' check (role in ('player','moderator','admin')),
  is_banned boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists profiles_username_idx on public.profiles(username);
create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_ban_idx on public.profiles(is_banned);

-- =========================
-- 2) 比赛记录
-- =========================
create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  played_at timestamptz not null default now(),
  player_a_id uuid not null references public.profiles(id),
  player_b_id uuid not null references public.profiles(id),
  score_a integer not null check (score_a >= 0 and score_a <= 99),
  score_b integer not null check (score_b >= 0 and score_b <= 99),
  competition_id text not null check (competition_id in ('friendly','club','school_qualifier','district_qualifier','school_official')),
  submitted_by uuid not null references public.profiles(id),
  status text not null default 'pending_opponent' check (status in ('pending_opponent','approved','rejected','cancelled')),
  opponent_confirmed_at timestamptz,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  note text,
  constraint match_players_distinct check (player_a_id <> player_b_id),
  constraint match_score_distinct check (score_a <> score_b),
  constraint match_submitter_is_participant check (submitted_by = player_a_id or submitted_by = player_b_id)
);

create index if not exists matches_played_at_idx on public.matches(played_at, created_at, id);
create index if not exists matches_status_idx on public.matches(status);
create index if not exists matches_a_idx on public.matches(player_a_id);
create index if not exists matches_b_idx on public.matches(player_b_id);
create index if not exists matches_submitter_idx on public.matches(submitted_by);

-- =========================
-- 3) 管理员操作日志
-- =========================
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id),
  action text not null,
  target_type text not null,
  target_id text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);

-- =========================
-- 4) 安全函数
-- =========================
create or replace function private.current_profile_role()
returns text
language sql
security definer
set search_path = ''
stable
as $$
  select p.role
  from public.profiles p
  where p.id = (select auth.uid())
$$;

create or replace function private.is_staff()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.is_banned = false
      and p.role in ('admin','moderator')
  )
$$;

create or replace function private.is_admin()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and p.is_banned = false
      and p.role = 'admin'
  )
$$;

-- =========================
-- 5) 注册后自动建立 profile
-- =========================
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, real_name, username)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'real_name'), ''), '未命名选手'),
    lower(trim(new.raw_user_meta_data ->> 'username'))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

-- =========================
-- 6) 保护账号权限字段
-- 普通用户只能修改自己的 real_name；role / is_banned 只能由 admin 修改。
-- =========================
create or replace function private.protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.username is distinct from new.username then
    raise exception '用户名不可修改。';
  end if;

  if old.role is distinct from new.role or old.is_banned is distinct from new.is_banned then
    if (select auth.uid()) is not null and not private.is_admin() then
      raise exception '只有 admin 可以修改账号角色或封禁状态。';
    end if;
    if (select auth.uid()) is not null and old.id = (select auth.uid()) then
      raise exception '为了避免把自己锁在系统外，不能修改自己的角色或封禁状态。';
    end if;
  end if;

  if old.real_name is distinct from new.real_name then
    if old.id <> (select auth.uid()) and not private.is_admin() then
      raise exception '没有权限修改该选手姓名。';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists protect_profile_fields on public.profiles;
create trigger protect_profile_fields
before update on public.profiles
for each row execute function private.protect_profile_fields();

-- =========================
-- 7) 比赛状态与不可变字段保护
-- =========================
create or replace function private.protect_match_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.played_at is distinct from new.played_at
     or old.player_a_id is distinct from new.player_a_id
     or old.player_b_id is distinct from new.player_b_id
     or old.score_a is distinct from new.score_a
     or old.score_b is distinct from new.score_b
     or old.competition_id is distinct from new.competition_id
     or old.submitted_by is distinct from new.submitted_by
  then
    raise exception '比赛核心信息不可修改，如需更正请撤销后重新提交。';
  end if;

  if old.status = 'pending_opponent' then
    if not private.is_staff() then
      if new.status not in ('approved','rejected') then
        raise exception '普通选手只能确认或拒绝待确认比赛。';
      end if;
      if old.player_a_id <> (select auth.uid()) and old.player_b_id <> (select auth.uid()) then
        raise exception '只有比赛双方可以确认比赛。';
      end if;
      if old.submitted_by = (select auth.uid()) then
        raise exception '提交比赛的一方不能自己确认自己的记录。';
      end if;
      if new.status = 'approved' then
        new.opponent_confirmed_at = now();
      end if;
    end if;
  elsif old.status = 'approved' then
    if not private.is_staff() then
      raise exception '已生效的比赛只能由管理员/副管理员撤销。';
    end if;
    if new.status <> 'cancelled' then
      raise exception '已生效比赛只能撤销。';
    end if;
  elsif old.status in ('rejected','cancelled') then
    if old.status <> new.status then
      raise exception '已拒绝或已撤销的比赛不能再次修改。';
    end if;
  end if;

  if new.status in ('approved','rejected','cancelled') and new.reviewed_by is null then
    new.reviewed_by = (select auth.uid());
    new.reviewed_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists protect_match_update on public.matches;
create trigger protect_match_update
before update on public.matches
for each row execute function private.protect_match_update();

-- 自动记录 admin / moderator 操作
create or replace function private.audit_match_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status is distinct from old.status then
    insert into public.audit_logs(actor_id, action, target_type, target_id, detail)
    values (
      (select auth.uid()),
      case
        when new.status = 'approved' then 'approve_match'
        when new.status = 'rejected' then 'reject_match'
        when new.status = 'cancelled' then 'cancel_match'
        else 'update_match'
      end,
      'match',
      new.id::text,
      jsonb_build_object('old_status', old.status, 'new_status', new.status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists audit_match_change on public.matches;
create trigger audit_match_change
after update on public.matches
for each row execute function private.audit_match_change();

create or replace function private.audit_profile_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.role is distinct from new.role or old.is_banned is distinct from new.is_banned then
    insert into public.audit_logs(actor_id, action, target_type, target_id, detail)
    values (
      (select auth.uid()),
      'update_account',
      'profile',
      new.id::text,
      jsonb_build_object(
        'old_role', old.role,
        'new_role', new.role,
        'old_banned', old.is_banned,
        'new_banned', new.is_banned
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists audit_profile_change on public.profiles;
create trigger audit_profile_change
after update on public.profiles
for each row execute function private.audit_profile_change();

-- =========================
-- 8) RLS
-- =========================
alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.audit_logs enable row level security;

-- 清掉常见默认权限，随后按最小权限重新授予。
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.matches from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

grant select on table public.profiles to anon, authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update on table public.matches to authenticated;
grant select on table public.matches to anon;
grant select on table public.audit_logs to authenticated;

-- profiles：榜单需要所有访客可看基础选手资料。
drop policy if exists profiles_public_read on public.profiles;
create policy profiles_public_read
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update
on public.profiles for update
to authenticated
using ((select auth.uid()) = id or (select private.is_admin()))
with check ((select auth.uid()) = id or (select private.is_admin()));

-- matches：访客只能看已生效比赛；登录用户额外能看自己涉及的待确认/已拒绝记录。
drop policy if exists matches_public_read on public.matches;
create policy matches_public_read
on public.matches for select
to anon, authenticated
using (
  status = 'approved'
  or (
    auth.uid() is not null
    and (submitted_by = (select auth.uid()) or player_a_id = (select auth.uid()) or player_b_id = (select auth.uid()))
  )
  or (select private.is_staff())
);

drop policy if exists matches_submit on public.matches;
create policy matches_submit
on public.matches for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and submitted_by = (select auth.uid())
  and (player_a_id = (select auth.uid()) or player_b_id = (select auth.uid()))
  and status = 'pending_opponent'
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and p.is_banned = false
  )
);

drop policy if exists matches_update_participants on public.matches;
create policy matches_update_participants
on public.matches for update
to authenticated
using (
  (
    status = 'pending_opponent'
    and submitted_by <> (select auth.uid())
    and (player_a_id = (select auth.uid()) or player_b_id = (select auth.uid()))
    and exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_banned = false)
  )
  or (select private.is_staff())
)
with check (
  (select private.is_staff())
  or (
    status in ('approved','rejected')
    and submitted_by <> (select auth.uid())
    and (player_a_id = (select auth.uid()) or player_b_id = (select auth.uid()))
  )
);

-- audit log 仅 admin 可查看；副管理员不看详细审计日志，减少敏感信息暴露。
drop policy if exists audit_admin_read on public.audit_logs;
create policy audit_admin_read
on public.audit_logs for select
to authenticated
using ((select private.is_admin()));

-- 不允许通过 Data API 直接删比赛/账号；撤销采用 status='cancelled'，审计更完整。

-- =========================
-- 9) Realtime
-- =========================
-- Supabase Realtime 的 Postgres Changes 需要表加入 supabase_realtime publication。
do $$
begin
  begin
    alter publication supabase_realtime add table public.profiles;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.matches;
  exception when duplicate_object then null;
  end;
end;
$$;

-- =========================
-- 10) 首个 admin
-- =========================
-- 注册第一个账号后，在 SQL Editor 执行：
-- update public.profiles set role = 'admin' where username = '你的用户名';
